### ISSUE TITLE
If URL changes the new URL is not downloaded

### ISSUE THREAD

**Issue by toadle** [yutailang0119/SBPAsyncImage#16] opened 2021-07-25 19:39 UTC
Hey guys, 

I'm pretty new to SwiftUI therefore I'm not a big help fixing this, but I noticed that when changing the URL of the AsyncImage the new URL is not downloaded an displayed. I'm guessing the view needs to be destroyed first?

Here is what I'm using and what does not work:

```
...
if(libraryArtwork != nil) {
            AsyncImage(url: libraryArtwork!.artworkUrl(width: urlResolution(), height: urlResolution())!, content: { image in
                image.resizable()
            }, placeholder: {
                Rectangle().frame(width: width, height: width).foregroundColor(.gray)
            }).frame(width: width, height: width)
        } else {
            Rectangle().frame(width: width, height: width).foregroundColor(.gray)
        }
...
```

So in this case the `libraryArtwork` might be changed externally because it is coming from the viewModel.

Is the intended behaviour. Can I fix this somehow?

**Comment by yutailang0119** [comment] 2021-08-03 03:38
Hmm, I confirmed that SBPAsyncImage behaves differently with SwiftUI.AsyncImage.
It seems that onAppear is not called in ContentBody when the URL changes.
https://github.com/yutailang0119/SBPAsyncImage/blob/9033e10e719f0cfe670fc81c3278a1f7e92dd25b/Sources/SBPAsyncImage/BackportAsyncImage.swift#L124-L130

I'm thinking of solution.

<hr>

I was able to reproduce it with following code.

```swift
struct ContentView: View {
    @State var isBool: Bool = true

    var body: some View {
        VStack {
            AsyncImage(url: url)
            Button("toggle") {
                isBool.toggle()
            }
        }
    }

    private var url: URL? {
        isBool ?
        URL(string: "http://httpbin.org/image/png")
        : URL(string: "http://httpbin.org/image/webp")
    }
}
```

**Comment by toadle** [comment] 2021-08-03 10:07
I've tried another Package `SDWebImageSwiftUI`.

They have the same problem, but solved it in a hacky way: https://github.com/SDWebImage/SDWebImageSwiftUI/blob/336d3f6d3b53729c1f274bf6b75f4532ada116eb/SDWebImageSwiftUI/Classes/WebImage.swift#L58

**Comment by malhal** [comment] 2021-08-22 10:43
> Hey guys,
> 
> I'm pretty new to SwiftUI therefore I'm not a big help fixing this, but I noticed that when changing the URL of the AsyncImage the new URL is not downloaded an displayed. I'm guessing the view needs to be destroyed first?
> 
> Here is what I'm using and what does not work:
> 
> ```
> ...
> if(libraryArtwork != nil) {
>             AsyncImage(url: libraryArtwork!.artworkUrl(width: urlResolution(), height: urlResolution())!, content: { image in
>                 image.resizable()
>             }, placeholder: {
>                 Rectangle().frame(width: width, height: width).foregroundColor(.gray)
>             }).frame(width: width, height: width)
>         } else {
>             Rectangle().frame(width: width, height: width).foregroundColor(.gray)
>         }
> ...
> ```
> 
> So in this case the `libraryArtwork` might be changed externally because it is coming from the viewModel.
> 
> Is the intended behaviour. Can I fix this somehow?

Instead of generating the url when you init AsyncImage, if you create a new View struct and take in width and height as params then set create the url and assign it to a let, then create AsyncImage using the url created, it usually solves problems like this because this is how SwiftUI works - body is only called if the View's lets are different. Because you are generating the url inside body you broke SwiftUI's change tracking.

**Closed** 2021-11-11 09:18 UTC
